#!/usr/bin/env python3
"""Generate a RESTORE.md tailored to the agent's config."""
import json, sys
from datetime import datetime

config_file = sys.argv[1]
output_file = sys.argv[2]

with open(config_file) as f:
    c = json.load(f)

name = c.get("agent_name", "Agent")
emoji = c.get("agent_emoji", "")
workspace = c.get("workspace", "~/.openclaw/workspace")
pfiles = c.get("personality_files", ["SOUL.md", "IDENTITY.md", "USER.md", "AGENTS.md", "MEMORY.md", "TOOLS.md"])

pfiles_list = "\n".join(f"- `{f}`" for f in pfiles)

content = f"""# RESTORE.md — {name} {emoji} Personality Restoration Guide

This backup contains everything needed to restore the agent's personality, memory,
and configuration onto a fresh OpenClaw installation.

## Quick Restore Steps

### 1. Prerequisites
- A running OpenClaw installation (gateway active)
- `p7zip-full` for future backups
- Python 3 with smtplib (for email delivery)

### 2. Restore Personality Files
Copy to `{workspace}/`:
{pfiles_list}

### 3. Restore Memory
Copy `memory/` to `{workspace}/memory/`

### 4. Restore Secrets
Copy `secrets/` to the secrets directory.
**NEVER expose these publicly.**

### 5. Restore Config
Copy `config/openclaw.json` to `~/.openclaw/openclaw.json`

### 6. Restore Projects
Copy `projects/` to `{workspace}/projects/`
Run `npm install` in projects that need it.

### 7. Restore Scripts
Copy `scripts-workspace/` to `{workspace}/scripts/`

### 8. Set Up Daily Backup
Re-enable the cron job for automated backups.

---
*Generated by personality-backup skill on {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}*
"""

with open(output_file, "w") as f:
    f.write(content)

print("RESTORE.md generated.")
