class Reporter {
  constructor(config) {
    this.config = config;
  }

  async generate(cryptoAPI, stockAPI) {
    const date = new Date().toLocaleDateString('zh-CN', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      weekday: 'long'
    });

    let report = `# 📊 投资组合日报\n\n`;
    report += `**生成时间**: ${date}  \n`;
    report += `**货币**: ${this.config.currency || 'USD'}  \n\n`;
    report += `---\n\n`;

    // Crypto section
    if (this.config.watchlist.crypto?.length > 0) {
      report += `## 💎 加密货币\n\n`;
      
      for (const symbol of this.config.watchlist.crypto) {
        try {
          const data = await cryptoAPI.getPrice(symbol.toLowerCase());
          const price = data?.usd || 'N/A';
          const change24h = data?.usd_24h_change;
          
          report += `### ${symbol.toUpperCase()}\n`;
          report += `- **价格**: $${price.toLocaleString()}\n`;
          if (change24h !== undefined) {
            const emoji = change24h >= 0 ? '📈' : '📉';
            report += `- **24h 变化**: ${emoji} ${change24h > 0 ? '+' : ''}${change24h.toFixed(2)}%\n`;
          }
          report += `\n`;
        } catch (e) {
          report += `### ${symbol.toUpperCase()}\n- 数据获取失败\n\n`;
        }
      }
    }

    // Stock section
    if (this.config.watchlist.stocks?.length > 0) {
      report += `## 📈 股票\n\n`;
      
      for (const symbol of this.config.watchlist.stocks) {
        try {
          const data = await stockAPI.getQuote(symbol);
          const emoji = data.change >= 0 ? '📈' : '📉';
          
          report += `### ${symbol}\n`;
          report += `- **价格**: $${data.price.toLocaleString()}\n`;
          report += `- **涨跌**: ${emoji} $${data.change > 0 ? '+' : ''}${data.change.toFixed(2)} (${data.changePercent > 0 ? '+' : ''}${data.changePercent.toFixed(2)}%)\n`;
          report += `- **货币**: ${data.currency}\n\n`;
        } catch (e) {
          report += `### ${symbol}\n- 数据获取失败\n\n`;
        }
      }
    }

    // Active alerts
    if (this.config.alerts?.length > 0) {
      report += `## 🔔 活跃警报\n\n`;
      const activeAlerts = this.config.alerts.filter(a => !a.triggered);
      
      if (activeAlerts.length === 0) {
        report += `暂无活跃警报\n\n`;
      } else {
        activeAlerts.forEach(alert => {
          report += `- **${alert.symbol}**: `;
          if (alert.above) report += `突破 $${alert.above.toLocaleString()}`;
          if (alert.below) report += `跌破 $${alert.below.toLocaleString()}`;
          if (alert.percent) report += `波动超过 ${alert.percent}%`;
          report += `\n`;
        });
        report += `\n`;
      }
    }

    report += `---\n\n`;
    report += `*Generated by Finance Watcher*  \n`;
    report += `*Data from CoinGecko & Yahoo Finance*  \n`;
    report += `*Powered by OpenClaw* 🐾`;

    return report;
  }
}

module.exports = Reporter;
