#!/usr/bin/env python3
import json
import os
import sys
import argparse
import urllib.request
from datetime import datetime

STATE_FILE = os.path.expanduser("~/memory/the_only_state.json")
CONFIG_FILE = os.path.expanduser("~/memory/the_only_config.json")
CANVAS_DIR = os.path.expanduser("~/clawd/canvas")

def load_config():
    if os.path.exists(CONFIG_FILE):
        with open(CONFIG_FILE, 'r') as f:
            return json.load(f)
    return {}

def push_to_webhooks(config, message):
    if "webhooks" not in config:
        return
    
    for platform, url in config["webhooks"].items():
        if not url:
            continue
        try:
            req = urllib.request.Request(url, method="POST")
            req.add_header('Content-Type', 'application/json')
            if platform == 'discord':
                data = json.dumps({"content": message}).encode()
            elif platform == 'telegram':
                data = json.dumps({"text": message}).encode()
            elif platform == 'whatsapp':
                data = json.dumps({"body": message}).encode()
            elif platform == 'feishu':
                data = json.dumps({"msg_type": "text", "content": {"text": message}}).encode()
            else:
                continue
            
            urllib.request.urlopen(req, data=data)
            print(f"✅ Pushed to {platform}.")
        except Exception as e:
            print(f"⚠️ Failed to push to {platform}: {e}")

def main():
    parser = argparse.ArgumentParser(description="The ONLY Engine — Multi-channel delivery")
    parser.add_argument("--payload", type=str, required=True, help="JSON string of items generated by the Agent")
    args = parser.parse_args()

    config = load_config()
    bot_name = config.get("name", "Xiao Hong")
    max_items = config.get("items_per_ritual", 5)
    frequency = config.get("frequency", "hourly")
    
    try:
        items = json.loads(args.payload)
    except json.JSONDecodeError:
        print("❌ Invalid JSON payload.")
        sys.exit(1)
        
    if len(items) > max_items:
        items = items[:max_items]
        
    # Extract canvas link from payload
    interactive_link = ""
    poll_question = ""
    for item in items:
        if item.get("type") == "interactive" and item.get("url"):
            interactive_link = item.get("url")
        if item.get("type") == "poll" and item.get("question"):
            poll_question = item.get("question")
    
    # Save delivery state
    state = {
        "last_delivery": datetime.now().isoformat(),
        "frequency": frequency,
        "items_delivered": len(items)
    }
    os.makedirs(os.path.dirname(STATE_FILE), exist_ok=True)
    with open(STATE_FILE, 'w') as f:
        json.dump(state, f)
        
    # Build notification message
    freq_label = "hourly" if frequency == "hourly" else "daily"
    msg = f"[{bot_name}] 📚 Your {freq_label} update is ready. {len(items)} items curated."
    if interactive_link:
        msg += f"\n🔗 Read: {interactive_link}"
    if poll_question:
        msg += f"\n🗳️ Poll: {poll_question}"
    
    push_to_webhooks(config, msg)
    print(f"✅ Engine processed {len(items)} items. Webhooks pinged.")

if __name__ == "__main__":
    main()
